version: '3.5'

services:
  etcd:
    container_name: milvus-oss-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - TZ=Asia/Shanghai
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-oss-standalone
    image: milvusdb/milvus:v2.5.16
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      # etcd 配置
      ETCD_ENDPOINTS: etcd:2379
      
      # OSS 配置
      MINIO_ADDRESS: oss-cn-hangzhou-internal.aliyuncs.com
      MINIO_PORT: 443 # 使用oss时一定要设置port，否则默认是9000
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_USE_VIRTUAL_HOST: true
      MINIO_USE_SSL: true
      MINIO_BUCKET_NAME: milvus-alioss
      MINIO_CLOUD_PROVIDER: aliyun
      # milvus 账号权限
      COMMON_SECURITY_AUTHORIZATION_ENABLED: true
      COMMON_SECURITY_SUPER_USERS: root
      COMMON_SECURITY_DEFAULT_ROOT_PASSWORD: admin123

    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"

networks:
  default:
    name: milvus