#!/bin/bash
echo "Mildoc index Starting... "

#在当前 shell 中加载 conda 初始化脚本
source /export/server/anaconda3/etc/profile.d/conda.sh
conda activate mildocindex

nohup python -u main.py --mode listen >> mildoc_index.log 2>&1 &

#nohup ：它的作用是让程序忽略 SIGHUP 信号。即使你关闭终端或断开 SSH 连接，程序也会继续运行
#-u ：参数表示强制 Python 的标准输出（stdout）和标准错误（stderr）不进入缓冲区，而是实时写入日志文件
#>> ：日志写入模式为追加
# 2>&1 ：将标准错误（2）重定向到标准输出（1）。配合前面的 >>，意味着正常日志和错误日志都会存入同一个文件。
# & ：让这条命令在后台执行，你可以立即在终端继续输入其他命令。